backend:
  name: github
  repo: Khan-digital/adnan-portfolio
  branch: main

media_folder: images
public_folder: /images

collections:
  - name: projects
    label: Projects
    folder: content/projects
    create: true
    slug: "{{slug}}"
    fields:
      - label: Project Title
        name: title
        widget: string

      - label: Short Description
        name: description
        widget: text

      - label: Cover Image
        name: image
        widget: image
        required: false

      - label: Role
        name: role
        widget: string
        required: false

      - label: Year
        name: year
        widget: string
        required: false

      - label: Case Study
        name: body
        widget: markdown
